"""Added destination_id to Review model

Revision ID: bb3451c67480
Revises: 46ea78419e09
Create Date: 2023-09-26 20:12:46.174028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3451c67480'
down_revision = '46ea78419e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_review_destination_id_destination'), 'destination', ['destination_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_review_destination_id_destination'), type_='foreignkey')
        batch_op.drop_column('destination_id')

    # ### end Alembic commands ###
